"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 6.0.6.
"""

from pathlib import Path

# 1ª CAMADA DE SEGURANÇA 

import os 
from dotenv import load_dotenv 

# Esta linha é como abrir o "cofre" (o arquivo .env) e colocar 
# todas as senhas na memória temporária do sistema, de forma segura.
load_dotenv()




BASE_DIR = Path(__file__).resolve().parent.parent


# PROTEÇÃO DA CHAVE MESTRA
# Em vez de deixar a senha escrita aqui, pedimos ao sistema para ir buscar a 'SECRET_KEY' que está escondida no .env

SECRET_KEY = os.getenv('SECRET_KEY')



# PROTEÇÃO DO MODO DE DEPURAÇÃO (TELA DE ERROS)
# O sistema só vai mostrar os detalhes dos erros, se lá no arquivo oculto .env estiver escrito exatamente 'True'.
DEBUG = os.getenv('DEBUG') == 'True'

ALLOWED_HOSTS = []




INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuarios',
    'autenticacao',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# Aqui é onde o sistema guarda as informações. Por enquanto, estamos usando
# um banco de dados simples (SQLite) que fica salvo num arquivo local.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# VALIDAÇÃO DE SENHA
# Regras de segurança para senhas de usuários (ex: não pode ser muito curta, não pode ser '123456')
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'



# CONFIGURAÇÃO CORS
# Aqui o backend Só aceita conversar e entregar dados se o pedido 
# vier de portas específicas. Isso impede que sites falsos roubem nossos dados.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]