# Generated by Django 5.2.13 on 2026-06-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=150)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("data_nascimento", models.DateField()),
                ("sexo_biologico", models.CharField(max_length=20)),
                ("telefone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("logradouro", models.CharField(max_length=150)),
                ("numero", models.CharField(max_length=20)),
                (
                    "complemento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("cep", models.CharField(max_length=10)),
                ("bairro", models.CharField(max_length=100)),
                ("cidade", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=2)),
                (
                    "hospital_clinica",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "medico_solicitante",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("crm", models.CharField(blank=True, max_length=20, null=True)),
                ("data_exame", models.DateField(blank=True, null=True)),
                ("tipo_exame", models.CharField(blank=True, max_length=100, null=True)),
                ("observacoes", models.TextField(blank=True, null=True)),
                ("alergias", models.TextField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
